{% set name = "matgl" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matgl-{{ version }}.tar.gz
  sha256: 8c832bcc3115d40dae623741f09ee952e2c651d1d7f0397be5e0a353530ca019

build:
  entry_points:
    - mgl = matgl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58.0.3
    - pip
  run:
    - torch-geometric
    - boto3
    - fsspec
    - numpy <3.0
    - torchdata
    - lightning <=2.6.0.dev20251123
    - pydantic
    - python >={{ python_min }}
    - ase
    - dgl <=2.4.0
    - pymatgen
    - pytorch-lightning
    - pytorch <=2.7.0

test:
  imports:
    - matgl
  commands:
    - pip check
    - mgl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  home: https://github.com/materialsvirtuallab/matgl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
