{% set name = "matgl" %}
{% set version = "1.2.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matgl-{{ version }}.tar.gz
  sha256: b2cda0c67f90e1659da8acf833046f377ffba4f80ed3ccdf2bcff85ccd286934

build:
  entry_points:
    - mgl = matgl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58.0.3
    - pip
  run:
    - boto3
    - fsspec
    - numpy <2.0
    - torchdata <=0.7.1
    - lightning <=2.5.1
    - pydantic
    - python >={{ python_min }}
    - ase
    - dgl <=2.2.0
    - pymatgen
    - pytorch-lightning
    - pytorch <=2.2.0

test:
  imports:
    - matgl
  commands:
    - pip check
    - mgl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  home: https://github.com/materialsvirtuallab/matgl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
