{% set name = "matgl" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matgl-{{ version }}.tar.gz
  sha256: 5ee0eda4b07e2f6a3d31e4a423757b965d4e0ec65c2f1e7bcb48d5def6669165

build:
  entry_points:
    - mgl = matgl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=58.0.3
    - pip
  run:
    - pydantic
    - python >=3.9
    - ase
    - dgl >=2.0.0
    - pymatgen
    - pytorch-lightning
    - pytorch <=2.2.1

test:
  imports:
    - matgl
  commands:
    - pip check
    - mgl --help
  requires:
    - pip

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  home: https://github.com/materialsvirtuallab/matgl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
