{% set name = "matgl" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matgl-{{ version }}.tar.gz
  sha256: 6b09b3a7a68a1f6fe47bed8c7408540353e46371e32c1a1ac2bde347a6885a14

build:
  entry_points:
    - mgl = matgl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58.0.3
    - pip
  run:
    - torchdata <0.8.0
    - lightning
    - pydantic
    - python >={{ python_min }}
    - ase
    - dgl >=2.0.0
    - pymatgen
    - pytorch-lightning
    - pytorch

test:
  imports:
    - matgl
  commands:
    - pip check
    - mgl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  home: https://github.com/materialsvirtuallab/matgl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
