{% set name = "matgl" %}
{% set version = "2.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matgl-{{ version }}.tar.gz
  sha256: 1a07b09edefbbfc803ca2247ded34b32e28bc635d0f8eaa2690991773d4f5e08

build:
  entry_points:
    - mgl = matgl.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58.0.3
    - pip
  run:
    - huggingface_hub >=0.24
    - pymatgen-core >=2026.4.16
    - pytorch_geometric
    - boto3
    - numpy <3.0
    - torchdata
    - pydantic
    - python >={{ python_min }}
    - ase
    - pymatgen
    - lightning <=2.6.1
    - pytorch

test:
  imports:
    - matgl
  commands:
    - pip check
    - mgl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  home: https://github.com/materialsvirtuallab/matgl
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
