schema_version: 1

context:
  name: matgl
  version: 2.2.1
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/matgl-${{ version }}.tar.gz
  sha256: 37e972d3a529e8a413e21b1c07d38aa3d320d6f926d457b3bda1219b899c587b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mgl = matgl.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=58.0.3
    - pip
  run:
    - huggingface_hub >=0.24
    - pymatgen-core >=2026.4.16
    - pytorch_geometric
    - boto3
    - numpy <3.0
    - torchdata
    - pydantic
    - python >=${{ python_min }}
    - ase
    - lightning <=2.6.1
    - pytorch
tests:
  - python:
      imports:
        - matgl
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - mgl --help

about:
  summary: MatGL is a framework for graph deep learning for materials science.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsvirtuallab/matgl

extra:
  recipe-maintainers:
    - jan-janssen
